#!/bin/sh

# This is convenience a wrapper to execute SamTextViewer.jar on *nix systems.  
# Put this script and ASCIIGenome.jar in a directory on you PATH e.g. in 
# /usr/local/bin or ~/bin/.
# You might need to change permission to execute it, e.g.
# chmod 755 SamTextViewer
#
#-Xmx2000m indicates 2000 mb of memory, adjust number up or down as needed

prefix=`dirname $(readlink $0 || echo $0)`
exec java -Xmx1500m -jar "$prefix"/ASCIIGenome.jar "$@"
