#!/bin/bash

# This is convenience a wrapper to execute ASCIIGenome.jar on *nix systems.  
# Put this script and ASCIIGenome.jar in a directory on you PATH e.g. in 
# /usr/local/bin or ~/bin/.
# You might need to change permission to execute it, e.g.
# chmod 755 ASCIIGenome 
#
#-Xmx2000m indicates 2000 mb of memory, adjust number up or down as needed

prefix=`dirname $(readlink $0 || echo $0)`
java -Djava.net.useSystemProxies=true -Xmx2500m -jar "$prefix"/ASCIIGenome.jar "$@"
#if [ "$?" == 0  ]
#then
#    clear
#fi
