import java.security.MessageDigest
import java.nio.file.Paths

apply plugin: 'java'
apply plugin: 'jacoco'

def jversion= JavaVersion.VERSION_17
java {
    sourceCompatibility= jversion
    targetCompatibility= jversion
}

if(JavaVersion.current() < jversion) {
    throw new GradleException("Java >= " + jversion + " is required but you are running " + JavaVersion.current())
}


/** Return the MD5 sum of the give File object */
ext.generateMD5 = { file ->
    def digest = MessageDigest.getInstance("MD5")
    file.eachByte( 4096 ) { buffer, length ->
        digest.update(buffer, 0 as byte, length)
    }
    new BigInteger(1, digest.digest()).toString(16).padLeft(32, '0')
}

/** Gunzip the given file. Same as `gunzip -c dir/myfile.txt.gz > dir/myfile.txt`. 
String filename must have extension .gz */
ext.gunzip = { filename ->
    File outfile = new File(filename.replaceFirst('\\.gz$', ''))
    outfile.withOutputStream { os ->
        os << resources.gzip(filename).read()
      }
}

tasks.register('prepareTestData') {
    doLast {
        String testDir = Paths.get(System.getProperty("user.dir"), 'test_data')

        File targetFile = new File(testDir, 'chr7.fa')
        String targetMD5 = "30c3693ead968844a769a90a801a900f"

        if (!targetFile.exists() || generateMD5(targetFile) != targetMD5) {
            File fgz = new File(testDir, targetFile.name + ".gz")
            gunzip(fgz.absolutePath)
            if (generateMD5(targetFile) != targetMD5) {
                throw new GradleException("Corrupted file " + targetFile)
            }
        }

        targetFile = new File(testDir, 'ALL.wex.union_illumina_wcmc_bcm_bc_bi.20110521.snps.exome.sites.vcf')
        targetMD5 = "6783ca5e6df2ce1075e1e0c924ad7d37"

        if (!targetFile.exists() || generateMD5(targetFile) != targetMD5) {
            File fgz = new File(testDir, targetFile.name + ".gz")
            gunzip(fgz.absolutePath)
            if (generateMD5(targetFile) != targetMD5) {
                throw new GradleException("Corrupted file " + targetFile)
            }
        }

        gunzip(Paths.get(testDir, "CEU.exon.2010_06.genotypes.vcf.gz").toString())
        gunzip(Paths.get(testDir, "ALL.wgs.mergedSV.v8.20130502.svs.genotypes.vcf.gz").toString())
    }
}

test {
    dependsOn prepareTestData
    useJUnit()

    testLogging {
        events "passed", "skipped", "failed"
        exceptionFormat = "full"
    }
    if (project.hasProperty('excludeTests')) {
        exclude project.property('excludeTests')
    }
}

repositories {
    mavenCentral()
    maven { url = 'https://jitpack.io' }
    maven { url = "https://repository.jboss.org/nexus/content/repositories/thirdparty-releases/" }
}

jar {
    duplicatesStrategy = DuplicatesStrategy.EXCLUDE
    manifest {
        attributes "Main-Class": "samTextViewer.Main"
    }
 
    from {
        configurations.runtimeClasspath.collect { it.isDirectory() ? it : zipTree(it) }
    }
}

dependencies {
    implementation "net.sourceforge.argparse4j:argparse4j:0.8.1"
    implementation "jline:jline:2.14.5"
    implementation "com.github.igvteam:igv:v2.6.3"
    implementation "log4j:log4j:1.2.17"
    implementation "com.github.samtools:htsjdk:5.0.0"
    implementation "org.apache.commons:commons-text:1.15.0"
    implementation "org.apache.commons:commons-lang3:3.5"
    implementation "org.apache.commons:commons-math3:3.6.1"
    implementation "commons-validator:commons-validator:1.6"
    implementation "commons-io:commons-io:2.6"
    implementation "com.esotericsoftware.yamlbeans:yamlbeans:1.13"
    implementation "com.itextpdf:itextpdf:5.5.13"
    implementation "com.google.guava:guava:24.0-android"
    implementation "com.google.code.gson:gson:2.8.2"
    implementation "org.biojava:biojava-genome:7.2.4"
    implementation "org.biojava:biojava-core:7.2.4"
    implementation 'org.biojava:biojava-alignment:7.2.4'
    // implementation "openchart:openchart:1.4.2"
    implementation "org.xerial:sqlite-jdbc:3.51.1.0"
    implementation "com.fasterxml.jackson.core:jackson-core:2.17.1"
    implementation  "com.fasterxml.jackson.dataformat:jackson-dataformat-yaml:2.17.1"
    implementation files('libs/bcf.jar')
    testImplementation 'junit:junit:4.12'
}

jacocoTestReport {
    dependsOn test

    classDirectories.setFrom(
        sourceSets.main.output
    )

    reports {
        xml.required = true
        html.required = true
    }
}
check.dependsOn jacocoTestReport
