name: CI
on: [push]
jobs:
  build-and-test:
    runs-on: 
      ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest, macos-latest]
        version: [17, 25]
    steps:
      - uses: actions/checkout@v6
      - uses: actions/setup-java@v5
        with:
          distribution: 'temurin'
          java-version: ${{ matrix.version }}

      - name: Install samtools (Linux)
        if: runner.os == 'Linux'
        run: |
          sudo apt-get update
          sudo apt-get install -y samtools

      - name: Install samtools (macOS)
        if: runner.os == 'macOS'
        run: |
          brew install samtools

      - name: Build and Test
        run: |
          ./gradlew build test jacocoTestReport
          cp ASCIIGenome build/libs/
          cd src/test/java
          chmod a+x integration_test.py
          ./integration_test.py

      - name: Upload coverage to Codecov
        env:
          CODECOV_TOKEN: ${{ secrets.CODECOV_TOKEN }}
        run: bash <(curl -s https://codecov.io/bash)
