name: CI
on: [push]
jobs:
  build-and-test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: '8'
      - name: Build and Test
        run: |
          ./gradlew test --tests samTextViewer.InteractiveInputTest.canHandleSessionNameNotFound
          # ./gradlew build test jacocoTestReport -PexcludeTests=**/TravisExcludedTest*
          # cp ASCIIGenome build/libs/
          # cd src/test/java
          # chmod a+x integration_test.py
          # ./integration_test.py
          # bash <(curl -s https://codecov.io/bash)
